# Generated by Django 4.2.4 on 2023-08-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0003_alter_message_options_rename_text_message_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="slug",
            field=models.SlugField(max_length=250, unique_for_date="publish"),
        ),
    ]
