# Generated by Django 4.2.4 on 2023-08-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0004_alter_message_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
